# Generated by Django 5.2.5 on 2025-08-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
