# Generated by Django 5.2.5 on 2025-08-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournamentapplication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration'), ('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='registration', max_length=20),
        ),
    ]
