# Generated by Django 5.2.5 on 2025-08-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_game_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover',
        ),
    ]
