# Generated by Django 5.2.5 on 2025-08-30 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_game_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='registration', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tournamentapplication',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_application'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_participant'),
        ),
    ]
