# Generated by Django 5.2.5 on 2025-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tournaments', '0002_alter_tournamentapplication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tournaments.game'),
        ),
    ]
