# Generated by Django 5.2.5 on 2025-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_game'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_is_dele_160694_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
    ]
